Dev
KozlovKA/PPVIS1_19 pull request #1
Opened 2020-04-27 10:39 UTC by KozlovKA

2020-04-27 10:44 UTC, Paulbel requested changes

2020-04-27 10:44 UTC, Paulbel commented on src/main/java/Last.java
> +                if ((ke.stateMask & SWT.CTRL) != 0) {
Почитать о различии & и &&

2020-04-27 10:45 UTC, Paulbel commented
Добавить логику самих групп

2020-04-27 11:03 UTC, Paulbel commented
Отображение по кругу должно быть универсальным - работать для любого кол-ва групп, а не только для 5

2020-04-27 17:22 UTC, KozlovKA commented
> Добавить логику самих групп
Добавил

2020-04-27 17:22 UTC, KozlovKA commented
> Отображение по кругу должно быть универсальным - работать для любого кол-ва групп, а не только для 5
Сделал

2020-04-27 17:27 UTC, KozlovKA commented on src/main/java/Last.java
> +                if ((ke.stateMask & SWT.CTRL) != 0) {
вроде все правильно ,мы используем & ke.stateMask и SWT.CTRL-возвращают интовые переменные а не булевые

2020-05-03 12:57 UTC, Paulbel requested changes
Исправить и прислать демо работы приложения(показать весь функционал)

2020-05-03 12:57 UTC, Paulbel commented on src/main/java/CheckButton.java
> +	void getTask4(Shell shell)
Дать понятное название

2020-05-11 10:53 UTC, Paulbel approved these changes

2020-05-18 18:45 UTC, merged